import React from 'react'
import { Page, Footer, GoldRule, Label, PageTitle, Body, TipsBox, WarningBox, GOLD, BLACK, WHITE, GRAY, GRAY_MID, GRAY_BORDER } from './components'

const content:React.CSSProperties={padding:'58px 56px 76px'}
const grid2:React.CSSProperties={display:'grid',gridTemplateColumns:'1fr 1fr',gap:18}
const panel:React.CSSProperties={border:`1px solid ${GRAY_BORDER}`,padding:18,background:WHITE}
const darkPanel:React.CSSProperties={padding:18,background:BLACK,color:WHITE}

function Stat({value,label,unit}:{value:string,label:string,unit?:string}){
  return <div style={{borderTop:`3px solid ${GOLD}`,background:GRAY,padding:'15px 13px'}}><div style={{fontFamily:"'Bebas Neue',sans-serif",fontSize:31,color:BLACK,lineHeight:1}}>{value}<small style={{fontFamily:"'Inter',sans-serif",fontSize:11,color:GRAY_MID,marginLeft:3}}>{unit}</small></div><div style={{fontFamily:"'Inter',sans-serif",fontSize:7.5,letterSpacing:'.11em',color:GRAY_MID,marginTop:6,textTransform:'uppercase'}}>{label}</div></div>
}

function Bullet({n,title,children}:{n:string,title:string,children:React.ReactNode}){
  return <div style={{display:'grid',gridTemplateColumns:'34px 1fr',gap:12,padding:'13px 0',borderBottom:`1px solid ${GRAY_BORDER}`}}><div style={{fontFamily:"'Bebas Neue',sans-serif",fontSize:23,color:GOLD}}>{n}</div><div><div style={{fontFamily:"'League Spartan',sans-serif",fontSize:12,fontWeight:800,color:BLACK,marginBottom:4}}>{title}</div><div style={{fontFamily:"'Inter',sans-serif",fontSize:10.5,lineHeight:1.55,color:'#555'}}>{children}</div></div></div>
}

function Macro({name,value,why}:{name:string,value:string,why:string}){
  return <div style={panel}><Label size={7}>{name}</Label><div style={{fontFamily:"'Bebas Neue',sans-serif",fontSize:30,color:BLACK}}>{value}</div><div style={{fontFamily:"'Inter',sans-serif",fontSize:9.5,lineHeight:1.55,color:'#555'}}>{why}</div></div>
}

export function P38_FatLossDivider(){
  return <Page dark><div style={{position:'absolute',right:-25,top:-30,fontFamily:"'Bebas Neue',sans-serif",fontSize:420,lineHeight:1,color:'rgba(255,255,255,.025)'}}>3</div><div style={{position:'absolute',left:56,top:'50%',transform:'translateY(-50%)',width:3,height:190,background:GOLD}}/><div style={{position:'absolute',left:80,right:56,top:'50%',transform:'translateY(-50%)'}}><Label>Parte Três · Perda de Gordura</Label><div style={{fontFamily:"'Bebas Neue',sans-serif",fontSize:14,letterSpacing:'.3em',color:'rgba(255,255,255,.4)',marginBottom:12}}>NOVO PERCURSO</div><div style={{fontFamily:"'League Spartan',sans-serif",fontSize:54,fontWeight:800,lineHeight:.98,color:WHITE}}>PERDER<br/><span style={{color:GOLD}}>GORDURA</span><br/>PRESERVAR MÚSCULO</div><GoldRule width={60}/><p style={{fontFamily:"'Inter',sans-serif",fontSize:13,lineHeight:1.75,color:'rgba(255,255,255,.52)',maxWidth:500,marginTop:20}}>Um plano sustentável para reduzir gordura corporal sem transformar a dieta numa punição nem abandonar o treino de força.</p></div><Footer pageNumber={36} chapter="Perda de Gordura" dark/></Page>
}

export function P39_FatLossFoundations(){
  return <Page><div style={content}><Label>Capítulo 23</Label><PageTitle size={42}>A BASE DA<br/><span style={{color:GOLD}}>PERDA DE GORDURA</span></PageTitle><Body style={{maxWidth:610,marginBottom:24}}>Perder gordura exige um défice energético mantido ao longo do tempo. O objetivo não é comer o mínimo possível: é criar um plano que consigas repetir enquanto proteges saúde, energia e massa muscular.</Body><div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:8,marginBottom:25}}><Stat value="−10 a −20" unit="%" label="Défice inicial prudente"/><Stat value="0,25–0,75" unit="kg" label="Ritmo semanal comum"/><Stat value="2+" unit="dias" label="Treino de força"/><Stat value="7–9" unit="h" label="Sono por noite"/></div><div style={grid2}><div><Label size={8} color={GRAY_MID}>As quatro prioridades</Label><Bullet n="01" title="DÉFICE CONTROLADO">Começa com uma redução moderada em relação à manutenção e ajusta através da tendência do peso.</Bullet><Bullet n="02" title="PROTEÍNA E SACIEDADE">Distribui proteína pelas refeições e usa alimentos ricos em fibra e água.</Bullet><Bullet n="03" title="FORÇA E MOVIMENTO">Mantém o treino de resistência e aumenta atividade diária de forma gradual.</Bullet><Bullet n="04" title="CONSISTÊNCIA">Avalia médias semanais, não um único número na balança.</Bullet></div><div><div style={darkPanel}><Label size={8}>O QUE MEDIR</Label>{['Peso médio semanal','Perímetro da cintura','Fotografias mensais','Força nos exercícios','Fome, sono e energia'].map(x=><div key={x} style={{padding:'9px 0',borderBottom:'1px solid rgba(255,255,255,.1)',fontFamily:"'Inter',sans-serif",fontSize:10.5,color:'rgba(255,255,255,.72)'}}>✓ {x}</div>)}</div><div style={{marginTop:14}}><WarningBox title="Saúde Primeiro">Gravidez, adolescência, historial de perturbações alimentares, doença metabólica ou medicação exigem acompanhamento de um profissional de saúde.</WarningBox></div></div></div></div><Footer pageNumber={37} chapter="Fundamentos da Perda de Gordura"/></Page>
}

export function P40_CalorieDeficit(){
  return <Page><div style={content}><Label>Capítulo 24</Label><PageTitle size={42}>CRIAR O<br/><span style={{color:GOLD}}>DÉFICE CERTO</span></PageTitle><Body style={{marginBottom:24}}>A manutenção é uma estimativa. Usa-a como ponto de partida, acompanha 2–3 semanas e ajusta com base na tendência real.</Body><div style={{...darkPanel,marginBottom:22}}><div style={{fontFamily:"'League Spartan',sans-serif",fontSize:10,letterSpacing:'.13em',color:GOLD,marginBottom:10}}>EXEMPLO PRÁTICO</div><div style={{display:'grid',gridTemplateColumns:'1fr auto 1fr auto 1fr',alignItems:'center',gap:12,textAlign:'center'}}><div><b style={{fontFamily:"'Bebas Neue',sans-serif",fontSize:32}}>2.500</b><small style={{display:'block',color:'rgba(255,255,255,.45)'}}>manutenção</small></div><div style={{color:GOLD}}>−</div><div><b style={{fontFamily:"'Bebas Neue',sans-serif",fontSize:32}}>375</b><small style={{display:'block',color:'rgba(255,255,255,.45)'}}>défice 15%</small></div><div style={{color:GOLD}}>=</div><div><b style={{fontFamily:"'Bebas Neue',sans-serif",fontSize:32,color:GOLD}}>2.125</b><small style={{display:'block',color:'rgba(255,255,255,.45)'}}>kcal/dia</small></div></div></div><div style={grid2}><div style={panel}><Label size={8}>PROCESSO DE AJUSTE</Label><Bullet n="1" title="ESTIMA">Calcula a manutenção ou usa 10–14 dias de ingestão e peso estáveis.</Bullet><Bullet n="2" title="REDUZ">Começa geralmente 10–20% abaixo da manutenção.</Bullet><Bullet n="3" title="OBSERVA">Compara médias de 7 dias durante pelo menos duas semanas.</Bullet><Bullet n="4" title="AJUSTA">Se a tendência estagnar, reduz ligeiramente ou acrescenta movimento.</Bullet></div><div><Label size={8} color={GRAY_MID}>Não confundas ruído com progresso</Label><Body style={{marginBottom:14}}>Sal, hidratos, ciclo menstrual, digestão e treino alteram água corporal. Uma subida isolada não significa ganho de gordura.</Body><TipsBox title="Usa a média semanal">Pesa-te em condições semelhantes e compara a média de sete dias com a semana anterior.</TipsBox><div style={{marginTop:14}}><WarningBox title="Evita extremos">Défices agressivos aumentam fome, fadiga e risco de perda de massa magra. Se surgirem tonturas, fraqueza persistente ou comportamentos alimentares preocupantes, interrompe e procura ajuda clínica.</WarningBox></div></div></div></div><Footer pageNumber={38} chapter="Défice Calórico"/></Page>
}

export function P41_FatLossMacros(){
  return <Page><div style={content}><Label>Capítulo 25</Label><PageTitle size={42}>MACROS PARA<br/><span style={{color:GOLD}}>SACIEDADE E FORÇA</span></PageTitle><Body style={{marginBottom:24}}>As calorias determinam a direção do peso. A distribuição dos alimentos influencia saciedade, recuperação e capacidade de manter o plano.</Body><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:10,marginBottom:24}}><Macro name="Proteína" value="1,6–2,2 g/kg" why="Referência prática para adultos saudáveis que treinam; individualiza conforme contexto e tolerância."/><Macro name="Gordura" value="20–35%" why="Evita cortar em excesso. Inclui azeite, peixe, ovos, frutos secos e sementes em porções medidas."/><Macro name="Hidratos" value="RESTO" why="Distribui o restante orçamento energético e concentra parte em torno do treino se isso ajudar a performance."/></div><div style={grid2}><div><Label size={8} color={GRAY_MID}>Constrói refeições saciantes</Label>{['1 fonte de proteína magra','1–2 porções de legumes','1 porção medida de hidratos','1 pequena fonte de gordura','Água ou bebida sem calorias'].map((x,i)=><Bullet key={x} n={String(i+1).padStart(2,'0')} title={x.toUpperCase()}>A quantidade final depende das calorias e necessidades individuais.</Bullet>)}</div><div><div style={{background:GRAY,padding:20,marginBottom:15}}><Label size={8}>VOLUME ALIMENTAR</Label><Body size={11}>Sopa de legumes, fruta inteira, batata, leguminosas, iogurte rico em proteína e vegetais ajudam a aumentar o volume da refeição sem concentrar demasiadas calorias.</Body></div><TipsBox title="Regra 80/20">Baseia a maioria da alimentação em opções nutritivas, mas reserva flexibilidade para alimentos de que gostas. A adesão vence a perfeição.</TipsBox><div style={{marginTop:15}}><WarningBox title="Sem alimentos proibidos">Um alimento isolado não bloqueia a perda de gordura. O padrão total, as porções e a frequência são mais importantes.</WarningBox></div></div></div></div><Footer pageNumber={39} chapter="Macros e Saciedade"/></Page>
}

export function P42_CuttingMealPlan(){
  const meals=[['PEQUENO-ALMOÇO','Iogurte skyr, aveia, frutos vermelhos e canela','430'],['ALMOÇO','Frango, arroz, grande porção de legumes e azeite medido','610'],['LANCHE','Fruta, queijo fresco batido e amêndoas','310'],['JANTAR','Peixe, batata, salada variada e sopa de legumes','590'],['CEIA OPCIONAL','Ovos, claras ou iogurte conforme fome e macros','220']]
  return <Page><div style={content}><Label>Capítulo 26</Label><PageTitle size={42}>DIA ALIMENTAR<br/><span style={{color:GOLD}}>DE DEFINIÇÃO</span></PageTitle><div style={{display:'flex',gap:8,margin:'18px 0 22px'}}><Stat value="≈2.160" unit="kcal" label="Exemplo diário"/><Stat value="≈165" unit="g" label="Proteína"/><Stat value="≈225" unit="g" label="Hidratos"/><Stat value="≈65" unit="g" label="Gordura"/></div><div style={{display:'grid',gap:8}}>{meals.map(([name,food,kcal],i)=><div key={name} style={{display:'grid',gridTemplateColumns:'42px 1fr 65px',alignItems:'center',gap:12,border:`1px solid ${GRAY_BORDER}`,padding:'13px 15px'}}><div style={{fontFamily:"'Bebas Neue',sans-serif",fontSize:22,color:GOLD}}>{String(i+1).padStart(2,'0')}</div><div><div style={{fontFamily:"'League Spartan',sans-serif",fontSize:11,fontWeight:800,color:BLACK}}>{name}</div><div style={{fontFamily:"'Inter',sans-serif",fontSize:9.5,color:'#555',marginTop:4}}>{food}</div></div><div style={{fontFamily:"'Bebas Neue',sans-serif",fontSize:20,textAlign:'right'}}>{kcal}<small style={{fontFamily:"'Inter',sans-serif",fontSize:8,color:GRAY_MID}}> kcal</small></div></div>)}</div><div style={{marginTop:18,display:'grid',gridTemplateColumns:'1fr 1fr',gap:12}}><TipsBox title="Personaliza">Este é apenas um exemplo. Ajusta porções, preferências, alergias, cultura alimentar e necessidades individuais.</TipsBox><div style={{background:BLACK,padding:'14px 16px',color:WHITE}}><Label size={7}>TROCAS SIMPLES</Label><div style={{fontFamily:"'Inter',sans-serif",fontSize:9.5,lineHeight:1.75,color:'rgba(255,255,255,.7)'}}>Frango ↔ peru ↔ tofu<br/>Arroz ↔ massa ↔ batata<br/>Skyr ↔ queijo batido ↔ soja<br/>Legumes: varia livremente</div></div></div></div><Footer pageNumber={40} chapter="Plano Alimentar de Definição"/></Page>
}

export function P43_TrainingAndCardio(){
  return <Page><div style={content}><Label>Capítulo 27</Label><PageTitle size={42}>TREINO, PASSOS<br/><span style={{color:GOLD}}>E CARDIO</span></PageTitle><Body style={{marginBottom:24}}>Durante a perda de gordura, o treino de força dá ao corpo uma razão para preservar músculo. O cardio aumenta gasto e saúde cardiovascular, mas não deve destruir a recuperação.</Body><div style={grid2}><div style={darkPanel}><Label size={8}>TREINO DE FORÇA</Label>{[['Frequência','2–4 sessões/semana'],['Objetivo','Manter técnica e cargas'],['Volume','Suficiente, recuperável'],['Esforço','Maioria das séries com 1–3 reps em reserva']].map(([a,b])=><div key={a} style={{display:'flex',justifyContent:'space-between',gap:14,padding:'12px 0',borderBottom:'1px solid rgba(255,255,255,.1)',fontFamily:"'Inter',sans-serif",fontSize:10}}><span style={{color:'rgba(255,255,255,.45)'}}>{a}</span><b style={{color:WHITE,textAlign:'right'}}>{b}</b></div>)}</div><div style={panel}><Label size={8}>ATIVIDADE AERÓBIA</Label><Bullet n="01" title="PASSOS">Define uma média sustentável e aumenta gradualmente.</Bullet><Bullet n="02" title="CARDIO MODERADO">Caminhada rápida, bicicleta ou elíptica são opções fáceis de recuperar.</Bullet><Bullet n="03" title="SAÚDE">Aponta para pelo menos 150 minutos moderados por semana e força em 2 dias.</Bullet></div></div><div style={{marginTop:20}}><TipsBox title="Ordem de prioridade">Se fizeres força e cardio na mesma sessão, realiza primeiro o treino mais importante para o teu objetivo. Se possível, separa-os por algumas horas.</TipsBox></div><div style={{marginTop:14}}><WarningBox title="Sinais de excesso">Queda contínua de força, dores persistentes, irritabilidade, sono pior e fadiga são sinais para reduzir volume, cardio ou défice.</WarningBox></div></div><Footer pageNumber={41} chapter="Treino e Cardio"/></Page>
}

export function P44_Plateaus(){
  return <Page><div style={content}><Label>Capítulo 28</Label><PageTitle size={42}>QUANDO O PESO<br/><span style={{color:GOLD}}>DEIXA DE DESCER</span></PageTitle><Body style={{marginBottom:24}}>Um plateau real não é um fim de semana sem mudança. Confirma primeiro que a média do peso e a cintura estão estáveis durante pelo menos 2–3 semanas.</Body><div style={grid2}><div><Label size={8} color={GRAY_MID}>Checklist antes de cortar calorias</Label>{['As porções continuam medidas?','Fins de semana estão incluídos?','Passos diminuíram sem perceberes?','Sono e stress pioraram?','Existe obstipação ou retenção de água?','A cintura também está estável?'].map((x,i)=><div key={x} style={{display:'flex',gap:10,padding:'11px 0',borderBottom:`1px solid ${GRAY_BORDER}`,fontFamily:"'Inter',sans-serif",fontSize:10.5,color:'#444'}}><span style={{color:GOLD}}>□</span>{x}</div>)}</div><div><div style={darkPanel}><Label size={8}>SE O PLATEAU FOR REAL</Label><div style={{fontFamily:"'Bebas Neue',sans-serif",fontSize:38,color:GOLD,marginBottom:4}}>ESCOLHE 1</div><Body size={10.5} color="rgba(255,255,255,.65)">Reduz aproximadamente 100–200 kcal por dia <strong style={{color:WHITE}}>ou</strong> acrescenta uma pequena quantidade de atividade. Mantém a alteração durante duas semanas antes de voltar a mexer.</Body></div><div style={{marginTop:15}}><TipsBox title="Diet break">Após muitas semanas de défice, um período planeado perto da manutenção pode ajudar adesão e treino. Não é uma semana sem limites.</TipsBox></div></div></div><div style={{marginTop:20,background:GRAY,padding:18}}><Label size={8}>A BALANÇA NÃO É O ÚNICO RESULTADO</Label><div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:8,textAlign:'center'}}>{['CINTURA','FOTOGRAFIAS','ROUPA','PERFORMANCE'].map(x=><div key={x} style={{background:WHITE,padding:13,fontFamily:"'League Spartan',sans-serif",fontSize:9,color:BLACK}}>{x}</div>)}</div></div></div><Footer pageNumber={42} chapter="Plateaus e Ajustes"/></Page>
}

export function P45_FatLossPlan(){
  const phases=[['01–02','PREPARAR','Medir ponto de partida, definir calorias, organizar compras e estabelecer passos.'],['03–05','CONSTRUIR','Repetir refeições-base, treinar força e melhorar consistência sem procurar perfeição.'],['06–08','AVALIAR','Comparar médias, cintura, fotografias e performance. Ajustar apenas se necessário.'],['09–10','CONSOLIDAR','Gerir eventos sociais, praticar flexibilidade e proteger sono e recuperação.'],['11–12','TRANSITAR','Rever resultados e subir gradualmente para manutenção quando o objetivo terminar.']]
  return <Page dark><div style={{...content,color:WHITE}}><Label>Capítulo 29 · Plano Prático</Label><div style={{fontFamily:"'League Spartan',sans-serif",fontSize:47,fontWeight:900,lineHeight:.98,marginBottom:12}}>12 SEMANAS<br/><span style={{color:GOLD}}>PARA DEFINIR</span></div><p style={{fontFamily:"'Inter',sans-serif",fontSize:12,lineHeight:1.7,color:'rgba(255,255,255,.52)',maxWidth:600,marginBottom:23}}>Usa este mapa como estrutura, não como corrida. O ritmo certo é aquele que mantém saúde, força e adesão.</p><div style={{display:'grid',gap:8}}>{phases.map(([weeks,title,text],i)=><div key={weeks} style={{display:'grid',gridTemplateColumns:'76px 115px 1fr',gap:14,alignItems:'center',padding:'14px 16px',border:'1px solid rgba(255,255,255,.1)',background:i===4?'rgba(212,175,55,.1)':'rgba(255,255,255,.025)'}}><div style={{fontFamily:"'Bebas Neue',sans-serif",fontSize:24,color:GOLD}}>{weeks}</div><div style={{fontFamily:"'League Spartan',sans-serif",fontSize:10,fontWeight:800,letterSpacing:'.1em'}}>{title}</div><div style={{fontFamily:"'Inter',sans-serif",fontSize:9.5,lineHeight:1.55,color:'rgba(255,255,255,.55)'}}>{text}</div></div>)}</div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12,marginTop:18}}><div style={{borderLeft:`3px solid ${GOLD}`,padding:'12px 15px',background:'rgba(212,175,55,.08)'}}><Label size={7}>REVISÃO SEMANAL</Label><div style={{fontFamily:"'Inter',sans-serif",fontSize:9.5,lineHeight:1.7,color:'rgba(255,255,255,.65)'}}>Peso médio · Cintura · Treino · Passos · Fome · Sono · Adesão</div></div><div style={{border:'1px solid rgba(255,255,255,.1)',padding:'12px 15px'}}><Label size={7}>META FINAL</Label><div style={{fontFamily:"'Inter',sans-serif",fontSize:9.5,lineHeight:1.7,color:'rgba(255,255,255,.65)'}}>Não apenas perder peso, mas aprender a manter o resultado com hábitos que cabem na tua vida.</div></div></div></div><Footer pageNumber={43} chapter="Plano de Perda de Gordura" dark/></Page>
}

